### ISSUE TITLE
Load Country Information without alert view

### ISSUE THREAD

**Issue by iehsan77** [sh3at90/CountrySelectorLib#1]
hi,

How to get country information without a load CountrySelectorLib alert view?

**Comment by mohshaat1990** [comment]
you can use this code 

let counterySelectorSearchBar  = CounterySelectorSearchBar()
counterySelectorSearchBar.delegate = self
counterySelectorSearchBar.getCountry(withRegionCode:"eg")

and implement the delegate you can find this in read me file

**Comment by iehsan77** [comment]
Thanks for your prompt response. I use this code but its return empty.

you can use this code

let counterySelectorSearchBar = CounterySelectorSearchBar()
counterySelectorSearchBar.delegate = self
let country = counterySelectorSearchBar.getCountry(withRegionCode:"pk"

country is empty...





*Ehsan-ul-haq*
----------------------------------------------------
(Software & Web Development)
IPhone Android Nokia (Development)
3D Animation Services

+923232430139
http://www.iehsan.com
https://www.linkedin.com/in/iehsan/
<http://www.linkedin.com/profile/view?id=39199691&trk=tab_pro>
http://www.facebook.com/iehsan

**Comment by mohshaat1990** [comment]
hi tried this code on the example   and returned Pakistan data

<img width="705" alt="Screen Shot 2020-03-23 at 5 00 33 PM" src="https://user-images.githubusercontent.com/11280137/77330470-1532ed80-6d28-11ea-988d-8a4e0b27bb59.png">

**Comment by iehsan77** [comment]
Yes you right I got this when select country on alert view but I need to
get when view did load call in uiviewcontroller





*Ehsan-ul-haq*
----------------------------------------------------
(Software & Web Development)
IPhone Android Nokia (Development)
3D Animation Services

+923232430139
http://www.iehsan.com
https://www.linkedin.com/in/iehsan/
<http://www.linkedin.com/profile/view?id=39199691&trk=tab_pro>
http://www.facebook.com/iehsan

**Comment by mohshaat1990** [comment]
you didn't need to show alert view you can write this code 

   let counterySelectorSearchBar  = CounterySelectorSearchBar()
        counterySelectorSearchBar.delegate = self
        counterySelectorSearchBar.getCountry(withRegionCode:"pk")

extension ViewController: CounterySelectorDelegate {
    
    func selectCountery(regionCode: String, country: Country?) {
        if let country = country {
            self.counteryImage.image = country.counterFlag
            self.countryNameLabel.text = country.name
            self.counteryCodeLabel.text = country.phoneCode
            self.mobileNumberExample.text = country.phoneNumberExample
        }
    }
    
    func selectCountery(country: Country) {
        self.counteryImage.image = country.counterFlag
        self.countryNameLabel.text = country.name
        self.counteryCodeLabel.text = country.phoneCode
        self.mobileNumberExample.text = country.phoneNumberExample
        self.dismiss(animated: true, completion: nil)
    }
}

and you will get country in delegate without select country

**Comment by iehsan77** [comment]
Thanks done


*Ehsan-ul-haq*
----------------------------------------------------
(Software & Web Development)
IPhone Android Nokia (Development)
3D Animation Services

+923232430139
http://www.iehsan.com
https://www.linkedin.com/in/iehsan/
<http://www.linkedin.com/profile/view?id=39199691&trk=tab_pro>
http://www.facebook.com/iehsan
